### ISSUE TITLE
Necromancer talent "Life Tap" description is incorrect

### ISSUE THREAD

**Issue by Roopo** [emmamai/vortex-indy#6]
Life tap appears to do nothing with hellspawn (possibly monster too, didn't test with monsters but do believe they fall under same category as this issue) No health gets depleted, and damage doesn't get increased.

**Comment by decino** [comment]
The life sapping bit has been deleted, instead it increases monster damage (and health!) by 20% per level. Corpulence is still somewhat of a counterpart as it increases monster damage by 10% per level and health by 40% per level. The talent descriptions (and names?) need an update. The damage increase is broken for hellspawns, yes.
