### ISSUE TITLE
Knight talent "mobility" doesn't seem to work

### ISSUE THREAD

**Issue by Roopo** [emmamai/vortex-indy#7]
Had 1 of 5 points in it before I actually tested, noticed max cooldown I could see in echo was 1.8 seconds.  After maxing it up to 5 of 5 points, yet again highest cooldown echo was 1.8 seconds.

**Comment by decino** [comment]
It was originally a 3-point talent (now 5), but the cooldown decrease is only applied to the first 3 levels. Anything upgraded above level 3 defaults to the initial 2.0 seconds delay.
